language: python
python: 2.7

install: 
- "sudo apt-get update"
- "sudo apt-get install python-dev python-pip libxml2-dev libxslt-dev zlib1g-dev"
- "pip install -r requirements.txt"

# build test cases and check for clean processing
script:
- "python test/gen_patterns.py > ./test.xml"
- "python matchmaker.py test.xml" 
